# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 01:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='labs',
            field=models.ManyToManyField(blank=True, to='labs.Lab'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
