# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
