# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20161031_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitionattachment',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='labs.Lab'),
        ),
    ]
