# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_lab_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(upload_to='lab-results'),
        ),
    ]
